apiVersion: v1
kind: Service
metadata:
  name: notes-api-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: notes-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
readinessProbe:
  httpGet:
    path: /api/v1/health
    port: 8000
  initialDelaySeconds: 5   # wait before first check
  periodSeconds: 5         # check every 5 seconds
  timeoutSeconds: 2        # request timeout

