services:
  frontend:
    container_name: frontend_fullstack_app
    image: frontend-nextjs:1.0.0
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    environment:
      NEXT_PUBLIC_API_URL: 'http://localhost:8000'
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    container_name: backend_fullstack_app
    image: backend-go:1.0.0
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres?sslmode=disable'
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    container_name: db_fullstack_app
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
